openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/test:
    get:
      summary: 'Test index'
      operationId: testIndex
      description: ''
      parameters:
        -
          in: query
          name: name
          description: 'Name description.'
          example: Jason
          required: true
          schema:
            type: string
            description: 'Name description.'
            example: Jason
        -
          in: query
          name: age
          description: 'Age description.'
          example: 17
          required: true
          schema:
            type: integer
            description: 'Age description.'
            example: 17
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 4
                  name: 'Jessica Jones'
                properties:
                  id:
                    type: integer
                    example: 4
                  name:
                    type: string
                    example: 'Jessica Jones'
        204:
          description: ''
        404:
          description: 'user not found'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'User not found'
                properties:
                  message:
                    type: string
                    example: 'User not found'
      tags:
        - Test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 10 characters.'
                  example: duwiz
                age:
                  type: integer
                  description: ''
                  example: 9
              required:
                - name
                - age
      security: []
tags:
  -
    name: Endpoints
    description: ''
  -
    name: Test
    description: "\nAPIs for test."
